//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showtime.Infrastructure.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Showtime.Infrastructure.UnitTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;Bad Request&quot;,&quot;message&quot;:&quot;Invalid value for page&quot;,&quot;code&quot;:0,&quot;status&quot;:400}.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string EmptyResponse {
            get {
                return ResourceManager.GetString("EmptyResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;url&quot;:&quot;https://www.tvmaze.com/shows/1/under-the-dome&quot;,&quot;name&quot;:&quot;Under the Dome&quot;,&quot;type&quot;:&quot;Scripted&quot;,&quot;language&quot;:&quot;English&quot;,&quot;genres&quot;:[&quot;Drama&quot;,&quot;Science-Fiction&quot;,&quot;Thriller&quot;],&quot;status&quot;:&quot;Ended&quot;,&quot;runtime&quot;:60,&quot;averageRuntime&quot;:60,&quot;premiered&quot;:&quot;2013-06-24&quot;,&quot;ended&quot;:&quot;2015-09-10&quot;,&quot;officialSite&quot;:&quot;http://www.cbs.com/shows/under-the-dome/&quot;,&quot;schedule&quot;:{&quot;time&quot;:&quot;22:00&quot;,&quot;days&quot;:[&quot;Thursday&quot;]},&quot;rating&quot;:{&quot;average&quot;:6.5},&quot;weight&quot;:99,&quot;network&quot;:{&quot;id&quot;:2,&quot;name&quot;:&quot;CBS&quot;,&quot;country&quot;:{&quot;name&quot;:&quot;United States&quot;,&quot;code&quot;:&quot;US&quot;,&quot;timezone&quot;:&quot;America/Ne [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Page0Response {
            get {
                return ResourceManager.GetString("Page0Response", resourceCulture);
            }
        }
    }
}
